name: Paper PDF
on:
  push:
    paths:
      - '.github/workflows/build_paper.yml'
      - 'paper/**'
      - 'presentation_TFPIE2022/**'
      - 'presentation_LambdaDays/**'
jobs:
  paper:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install python-pygments
        run: sudo apt-get install python-pygments

      - name: Build paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: engaging_fp_education.tex
          working_directory: paper
          args: -pdf -latexoption="-shell-escape" -file-line-error -halt-on-error -interaction=nonstopmode -outdir=build

      - name: Build presentation TFPIE2022
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation_TFPIE2022.tex
          working_directory: presentation_TFPIE2022
          args: -xelatex -latexoption="-shell-escape" -interaction=nonstopmode -outdir=build

      - name: Build presentation Lambda Days 2022 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation_LambdaDays.tex
          working_directory: presentation_LambdaDays
          args: -xelatex -latexoption="-shell-escape" -interaction=nonstopmode -outdir=build

      - name: Consolidate pdfs
        run: mkdir -p build/ && cp paper/build/engaging_fp_education.pdf presentation_TFPIE2022/build/presentation_TFPIE2022.pdf presentation_LambdaDays/build/presentation_LambdaDays.pdf build/

      - name: Upload pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_results
          path: build

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pdfs
          folder: build
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
